name: Bug Report 🔥
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping to improve this repository!
  - type: textarea
    attributes:
      label: Description of the issue
      description: Small description of the issue
      placeholder: |
        my problem is...
    validations:
      required: true
  - type: dropdown
    id: dropdown_id
    attributes:
      label: Do I want to contribute to fix it?
      description: Do I want to contribute to fix it?
      options:
        - "Yes"
        - "No"
        - "Maybe"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Something else?
      description: Something else to inform us?
    validations:
      required: false